In [ ]:
 # Using functions to generate data 

In [93]:
a33 = np.ones((3,4))

In [94]:
type(a33)

numpy.ndarray

In [95]:
a33

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [2]:
import numpy as np
a44 = np.zeros((2,4))

In [3]:
a44

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
import numpy as np
array1 = np.array([1,2,3])

In [6]:
array1

array([1, 2, 3])

In [7]:
import numpy as np
zeros_array = np.zeros((3,3))

In [8]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
ones_array = np.ones((1,1))

In [10]:
ones_array

array([[1.]])

### Specifying Data Type 

In [11]:
l = [1,2,3,4]

In [12]:
np.array(l,dtype = np.int32)

array([1, 2, 3, 4])

In [13]:
import numpy as np
int_array = np.array([1,2,3], dtype=np.int32)
float_array = np.array([0.1,0.2,0.3],dtype=np.float64)

In [16]:
int_array
float_array

array([0.1, 0.2, 0.3])

### Using arange and linspace

In [18]:
a44 = np.arange(0,12)

In [19]:
a44

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
a66 = np.arange(5,7)

In [21]:
a66

array([5, 6])

In [22]:
linspace_array_2 = np.linspace(0,10,6)
linspace_array_2

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [23]:
linspace_array_3 = np.linspace(0,15,4)
linspace_array_3

array([ 0.,  5., 10., 15.])

In [24]:
zeros_array = np.zeros((3,3))
ones_array = np.ones((2,4))
identity_matrix = np.eye(3)

In [25]:
random_array = np.random.rand(4,4)

In [26]:
random_array

array([[0.63550881, 0.61909202, 0.78951099, 0.57798449],
       [0.91321147, 0.74254036, 0.49031755, 0.90023461],
       [0.2360492 , 0.81386768, 0.12154749, 0.76106868],
       [0.69481511, 0.21530392, 0.18913337, 0.83415134]])

In [27]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Basic Indexing

In [31]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr[0])
print(arr[-1])

10
40


In [32]:
# 2D  Example 

matrix = np.array([[1,2,3],
                  [4,5,6]])

In [33]:
print(matrix[0,1])
print(matrix[1,2])      

2
6


In [35]:
# 1D Array Slicing

import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[1:4])
print(arr[:3])
print(arr[::2])
print(arr[::-1])

[20 30 40]
[10 20 30]
[10 30 50]
[50 40 30 20 10]


In [36]:
# 2D Array Slicing

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(matrix[0:2,1:3])

[[2 3]
 [5 6]]


In [50]:
print(matrix[2:3,1:2])

[[8]]


In [57]:
print(matrix[1:2,1:3])

[[5 6]]


In [66]:
# NumPy View 

a = np.array([1,2,3,4])
b = a[1:3]
b[0] = 99
print(a)

[ 1 99  3  4]


In [67]:
a = np.array([1,2,3,4])

In [68]:
b = a[1:3]

In [69]:
a

array([1, 2, 3, 4])

In [70]:
b

array([2, 3])

In [ ]:
# Copy

a = np.array([1,2,3,4])

In [71]:
b = a[1:3].copy()

In [72]:
b[0] = 99

In [73]:
print(a)

[1 2 3 4]


In [74]:
print(b)

[99  3]


In [76]:
# shape 
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [77]:
# Reshape 
a = np.arange(12)

In [78]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
b = a.reshape(3,4)

In [82]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
c = a.reshape(12,1)

In [84]:
c

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [87]:
# transpose
arr_3d = np.array([[0,1,2,3],
                   [4,5,6,7],
                   [8,9,10,11]])

In [89]:
arr_3d.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])