### RANDOM NUMBER GENERATION

In [1]:
import numpy as np

In [2]:
#Uniform distribution
uniform=np.random.rand(3,3)
print("Uniform distribution:\n",uniform)

Uniform distribution:
 [[0.78877043 0.54792435 0.53201528]
 [0.74578233 0.97548885 0.79681259]
 [0.00695674 0.52635504 0.78010668]]


In [10]:
#normal distribution
normal=np.random.randn(3,3)
print("normal distribution:\n",normal)

normal distribution:
 [[ 1.07467732  0.48261985 -0.70324063]
 [ 0.41456898 -0.55161414  0.62307281]
 [-2.16388745  1.37770324 -0.79312023]]


In [5]:
arr=np.array([1,2,3,4,5])

In [6]:
np.where(arr>3)

(array([3, 4], dtype=int64),)

In [7]:
print("where>3:",np.where(arr>3))

where>3: (array([3, 4], dtype=int64),)


In [12]:
np.where(arr<=2)

(array([0, 1], dtype=int64),)

In [13]:
arr=np.array([1,2,3,4,5])

In [14]:
np.argmax(arr)

4

In [15]:
np.argmin(arr)

0

In [16]:
sorted_arr=np.array([1,3,5,7])

In [17]:
np.searchsorted(sorted_arr,6)

3

In [18]:
np.searchsorted(sorted_arr,100)

4

In [19]:
np.searchsorted(sorted_arr,0)

0

In [20]:
arr=np.array([1,2,3,4,5])

In [21]:
print("extract>3:",np.extract(arr>3,arr))

extract>3: [4 5]


In [29]:
#mean calculation
arr=np.array([1,2,3,4,5])

In [30]:
print("mean value:",np.mean(arr))

mean value: 3.0


In [31]:
np.mean(arr)

3.0

In [36]:
#equal parts split
arr=np.array([1,2,3,4,5,6])


np.split(arr,3)


[array([1, 2]), array([3, 4]), array([5, 6])]

In [37]:
#split at specific positions

In [38]:
np.split(arr,[1,4])

[array([1]), array([2, 3, 4]), array([5, 6])]